### ISSUE TITLE
USER STORY: Vote Anonymously

### ISSUE THREAD

**Issue by devnickocodes** [devnickocodes/My-First-Agile-Project#3]
In order to **vote on the poll**, as a **user**, I can **choose to vote anonymously.**

# Acceptance Criteria 

* A radio button lets the user pick if they would like to remain anonymous or not
* The radio button should be on anonymous by default

## Tasks
 - [ ] #6
 - [ ] Set an annonymous by defult with HTML
 - [ ] style the radio buttons with css 
 - [ ] make it responsive
