### ISSUE TITLE
USER STORY: Poll Commenting

### ISSUE THREAD

**Issue by devnickocodes** [devnickocodes/My-First-Agile-Project#4]
In order to **vote on the poll**, as a **user**, I can **I can add additional comments that will go with my response.**

# Accepntance Criteria

* The comment section is a text field input
* The comment can be with max lenght of 500 characters

## Tasks
 - [ ] Write the HTML for the text field
 - [ ] Style the text field with CSS
 - [ ] Make the text field so it doesn't exceed 500 characters
